//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonEntities : DbContext
    {
        public PersonEntities(): base("name=PersonEntities")
        {
                 //will drop and create new db and seed
                Database.SetInitializer(new PersonDBInitializer());

            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public class PersonDBInitializer : DropCreateDatabaseAlways<PersonEntities>
        {
            protected override void Seed(PersonEntities context)
            {
                IList<Person> defaultStandards = new List<Person>();

                defaultStandards.Add(new Person() { LastName = "Davolio", FirstName = "Nancy", Age = 39, Address = "507 - 20th Ave. E.Apt. 2A", City = "Seattle", PostalCode = "98122", Interests = "coffee", PhotoPath = "https://images.pexels.com/photos/60883/girl-eyes-makeup-sexy-60883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Fuller", FirstName = "Andrew", Age = 21, Address = "908 W. Capital Way", City = "Tacoma", PostalCode = "98401", Interests = "donuts", PhotoPath = "https://images.pexels.com/photos/37547/suit-business-man-business-man-37547.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Leverling", FirstName = "Janet", Age = 38, Address = "722 Moss Bay Blvd.", City = "Kirkland", PostalCode = "98033", Interests = "dolls", PhotoPath = "https://images.pexels.com/photos/157622/woman-bench-stand-by-blonde-157622.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Peacock", FirstName = "Margaret", Age = 25, Address = "4110 Old Redmond Rd.", City = "Redmond", PostalCode = "98052", Interests = "race cars", PhotoPath = "https://images.pexels.com/photos/17840/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Buchanan", FirstName = "Steven", Age = 30, Address = "14 Garrett Hill", City = "London", PostalCode = "SW1 8JR", Interests = "programming", PhotoPath = "https://images.pexels.com/photos/193355/pexels-photo-193355.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Suyama", FirstName = "Michael", Age = 19, Address = "Coventry House Miner Rd.", City = "London", PostalCode = "EC2 7JR", Interests = "literature", PhotoPath = "https://images.pexels.com/photos/936043/pexels-photo-936043.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "King", FirstName = "Robert", Age = 15, Address = "Edgeham Hollow Winchester Way", City = "London", PostalCode = "RG1 9SP", Interests = "pokemon", PhotoPath = "https://images.pexels.com/photos/160933/girl-rabbit-friendship-love-160933.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Callahan", FirstName = "Laura", Age = 55, Address = "4726 - 11th Ave. N.E.", City = "Seattle", PostalCode = "98105", Interests = "pizza", PhotoPath = "https://images.pexels.com/photos/2712468/pexels-photo-2712468.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });
                defaultStandards.Add(new Person() { LastName = "Dodsworth", FirstName = "Anne", Age = 72, Address = "7 Houndstooth Rd.", City = "London", PostalCode = "WG2 7LT", Interests = "bad decisions", PhotoPath = "https://images.pexels.com/photos/2838056/pexels-photo-2838056.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" });

                context.People.AddRange(defaultStandards);
                base.Seed(context);

            }
        }
    }
   
}
